/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.create-dataset.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ifTable.h"
#include <net-snmp/agent/table_data.h>
#include <stdio.h> // Добавлено для snprintf

/** Initialize the ifTable table by defining its contents and how it's structured */
void
initialize_table_ifTable(void)
{
    const oid ifTable_oid[] = {1,3,6,1,4,1,9999,2,2};
    netsnmp_table_data_set *table_set;
    netsnmp_table_row *row;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("ifTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_ifTable",
                "adding indexes to table ifTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: ifIndex */
                           0);

    DEBUGMSGTL(("initialize_table_ifTable",
                "adding column types to table ifTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_IFINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFDESCR, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_IFTYPE, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFMTU, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFSPEED, ASN_GAUGE, 0,
                                            NULL, 0,
                                            COLUMN_IFPHYSADDRESS, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_IFADMINSTATUS, ASN_INTEGER, 1,
                                            NULL, 0,
                                            COLUMN_IFOPERSTATUS, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_IFLASTCHANGE, ASN_TIMETICKS, 0,
                                            NULL, 0,
                                            COLUMN_IFINOCTETS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINNUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINDISCARDS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFINUNKNOWNPROTOS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTOCTETS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTNUCASTPKTS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTDISCARDS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTERRORS, ASN_COUNTER, 0,
                                            NULL, 0,
                                            COLUMN_IFOUTQLEN, ASN_GAUGE, 0,
                                            NULL, 0,
                                            COLUMN_IFSPECIFIC, ASN_OBJECT_ID, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("ifTable", ifTable_handler,
                                                        ifTable_oid,
                                                        OID_LENGTH(ifTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);

    for (int i = 1; i <= 1; i++) {
        row = netsnmp_create_table_data_row();

        long ifIndex_val = i;
        long admin_status = 1;       // up (1)
        long oper_status = 2;        // down (2)
        long last_change = 1387400;  // 3 hours 51 minutes 14 seconds (1387400)

        // Устанавливаем индекс строки (номер текущего порта)
        netsnmp_table_row_add_index(row, ASN_INTEGER, &ifIndex_val, sizeof(ifIndex_val));

        char descr[16];
        snprintf(descr, sizeof(descr), "F%d", i);
        netsnmp_set_row_column(row, COLUMN_IFDESCR, ASN_OCTET_STR, descr, strlen(descr));

        // COLUMN_IFADMINSTATUS: Административное состояние
        netsnmp_set_row_column(row, COLUMN_IFADMINSTATUS, ASN_INTEGER, (const char *)&admin_status, sizeof(admin_status));

        // COLUMN_IFOPERSTATUS: Операционное состояние
        netsnmp_set_row_column(row, COLUMN_IFOPERSTATUS, ASN_INTEGER, (const char *)&oper_status, sizeof(oper_status));

        // COLUMN_IFLASTCHANGE: Время последнего изменения (Тип ASN_TIMETICKS!)
        netsnmp_set_row_column(row, COLUMN_IFLASTCHANGE, ASN_TIMETICKS, (const char *)&last_change, sizeof(last_change));

        // Добавляем заполненную строку в наш датасет
        netsnmp_table_dataset_add_row(table_set, row);
    }
}

/** Initializes the ifTable module */
void
init_ifTable(void)
{
    /* here we initialize all the tables we're planning on supporting */
    initialize_table_ifTable();
}

/** handles requests for the ifTable table, if anything else needs to be done */
int
ifTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* Нам не нужно здесь ничего делать руками, так как встроенный 
       dataset-обработчик net-snmp сам автоматически отдаст данные из памяти. */
    return SNMP_ERR_NOERROR;
}